version: "3.8"

services:
  authservice:
    image: authservice:1.0
    container_name: authservice
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app_network

  userservice:
    image: userservice:1.0
    container_name: userservice
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - authservice
    networks:
      - app_network

  reviewservice:
    image: reviewservice:1.0
    container_name: reviewservice
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - authservice
      - userservice
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
